name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: '5.4'

      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v6

      - name: Install Teal + Cyan
        run: |
          luarocks install tl
          luarocks install cyan

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Type check + Build
        run: |
          bun install
          bun run build:prepare
          bun run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: ./dist
